### ISSUE TITLE
Current form does not allow problem to do IO.

### ISSUE THREAD

**Issue by bradyt** [guillaume-nargeot/project-euler-haskell#3]
Thank you for this excellent layout, I am updating my old euler solutions mostly to your layout. But I'll have to think about how to call problem modules that do IO for for example data in a csv file.

**Comment by killy971** [comment]
Thanks! Indeed it might be good for problems that require a large input file.
I guess I didn't take an approach IO friendly as I didn't try to solve such problems so far (I believe all the ones I solved only require little input).
Will have a think of how to implement that nicely!

**Comment by bradyt** [comment]
I saw in your earlier commits `time` wasn't factored out yet, I think with that as a refactorable point and random internet searches, I put together the following hack that works for me for now. I haven't studied the surrounding concepts, like `seq`, etc, so I'm not sure if this is correct, and/or if it could be more cleanly coded. "It works enough" for now.

```haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where

import System.Environment (getArgs)
import P001 hiding (main)
import P002 hiding (main)
import P003 hiding (main)
...
 
import qualified Formatting as F
import Formatting.Clock
import System.Clock
import Text.Read (readMaybe)

thunk :: Int -> IO ()
thunk n = do
    putStr ("p" ++ show n ++ "\t")
    start <- getTime Monotonic
    x <- lookupSolution n
    end <- x `seq` getTime Monotonic
    F.fprint (timeSpecs F.% "\t") start end
    putStrLn x

main :: IO ()
main = do
    args <- getArgs
    let all = [1..59] ++ [ 62, 63, 67, 69, 71
                         , 76, 92, 97, 99, 206 ]
        ps = case args of
            []        -> all
            (arg0:[]) -> case (readMaybe arg0 :: Maybe Int) of
                 Just n  -> [n]
                 Nothing -> all
    mapM_ thunk ps

lookupSolution :: Int -> IO String
lookupSolution n = case lookup n problemMap of
    Nothing -> pure "no item in map"
    Just x  -> x
 
problemMap :: [(Int, IO String)]
problemMap =
    [ (1, pure $ show p001)
    , (2, pure $ show p002)
    , (3, pure $ show p003)
    , ...
    , (21, pure $ show p021)
    , (22, fmap   show p022)
    , (23, pure $ show p023)
    , ...
    ]
```
